syntax = "proto3";

package DC.Packet;

option java_package = "com.packets.item";
option java_outer_classname = "item";
option java_multiple_files = false;

message SItemMeta {
  string SoulHeart_AccountId = 1;
  string SoulHeart_PartyId = 2;
  string SoulHeart_NickName_origin = 3;
  string SoulHeart_NickName_streaming = 4;
  string SoulHeart_ItemSkinId = 5;
  uint32 AvailableValue = 6;
}

message SItem {
  uint64 itemUniqueId = 1;
  string itemId = 2;
  uint32 itemCount = 3;
  uint32 inventoryId = 4;
  uint32 slotId = 5;
  uint32 itemAmmoCount = 7;
  uint32 itemContentsCount = 8;
  repeated .DC.Packet.SItemProperty primaryPropertyArray = 9;
  repeated .DC.Packet.SItemProperty secondaryPropertyArray = 10;
  int32 lootState = 11;
  int32 originType = 12;
  string originNickName = 13;
  string originSteamingModeNickName = 14;
  repeated .DC.Packet.SItemEnchantInfo secondaryEnchantArray = 15;
  int32 tradable = 16;
  repeated .DC.Packet.SItemPermitted permittedAreaArray = 17;
}

message SItemProperties {
  repeated .DC.Packet.SItemProperty properties = 1;
}

message SItemProperty {
  string propertyTypeId = 1;
  int32 propertyValue = 2;
}

message SItemEnchantInfo {
  uint32 propertyIndex = 1;
  string materialItemId = 2;
}

message SItemEnchantInfos {
  repeated .DC.Packet.SItemEnchantInfo enchantInfos = 1;
}

message SItemPermittedInfos {
  repeated .DC.Packet.SItemPermitted permittedList = 1;
}

message SItemPermitted {
  int32 type = 1;
}

message SItems {
  repeated .DC.Packet.SItem item = 1;
}

message SPerk {
  uint32 index = 1;
  string perkId = 2;
}

message SSkill {
  uint32 index = 1;
  string skillId = 2;
}

message SSpell {
  uint32 slotIndex = 1;
  uint32 sequenceIndex = 2;
  string spellId = 3;
}

message SMusic {
  string musicId = 1;
  uint32 slotIndex = 2;
  uint32 sequenceIndex = 3;
}

message SShapeShift {
  string shapeShiftId = 1;
  uint32 slotIndex = 2;
  uint32 sequenceIndex = 3;
}

message SCUSTOMIZE_CHARACTER {
  string customizeCharacterId = 1;
  int32 isEquip = 2;
  int32 isNew = 3;
}

message SCUSTOMIZE_ITEM {
  string customizeItemId = 1;
  int32 isEquip = 2;
  int32 isNew = 3;
}

message SCUSTOMIZE_ARMOR_SKIN {
  string customizeArmorSkinId = 1;
  int32 isEquip = 2;
  int32 isNew = 3;
}

message SEMOTE {
  string emoteId = 1;
  int32 equipSlotIndex = 2;
  int32 isNew = 3;
}

message SCUSTOMIZE_ACTION {
  string customizeActionId = 1;
  int32 isEquip = 2;
  int32 isNew = 3;
}

message SCUSTOMIZE_LOBBY_EMOTE {
  string lobbyEmoteId = 1;
  int32 equipSlotIndex = 2;
  int32 isNew = 3;
}

message SCUSTOMIZE_LOBBY_SKIN {
  string lobbySkinId = 1;
  int32 isEquip = 2;
  int32 isNew = 3;
}

message SCUSTOMIZE_NAMEPLATE {
  string nameplateSkinId = 1;
  int32 isEquip = 2;
  int32 isNew = 3;
}

message SFriendItemRecoveryInfo {
  string friendAccountId = 1;
  string friendCharacterId = 2;
  repeated .DC.Packet.SItem recoveryItemList = 3;
}

message SGatheringHallItem {
  .DC.Packet.SItem origin = 1;
  float posX = 2;
  float posY = 3;
  float posZ = 4;
  float rotPitch = 5;
  float rotYaw = 6;
  float rotRoll = 7;
  int32 hallStatus = 8;
}

